lookbook-hq/lookbook

README.md
lib/lookbook/engine.rb

First of all, thank you for the amazing gem. 👏 I started using it for https://github.com/baoagency/polaris_view_components and it works great so far! It really makes the process of components development much easier.
In this PR I added additional configuration option to allow auto-reload on component changes:
```ruby
config.lookbook.listen_paths << Rails.root.join('../app/components')
```

Add listen paths config

---

Gemfile.lock
lookbook.gemspec

Without this, Lookbook fails to allow the app to bundle when running Rails from github and soon to be released the 7.0 alpha gems.
We dual-boot our rails application at work with two versions of Rails (Latest released 6.1 and then main from GitHub) and ever since the dependency was locked to ~> 6.0 this has prevented us from bundling.
I don't think there's anything specific in Lookbook that would break from Rails 7 but we'll certainly keep our eye out.

Relax the gemspec to work with Rails 7

---

lib/lookbook/parser.rb

ViewComponentContrib allows for component_name/preview.rb file structure. Changing the glob allows for lookbook to work, as long as the preview does not inherit from ViewComponentContrib::Preview (due to conflicting Preview templates and who does the rendering).

Enable previews to work with ViewComponentContrib

---

app/controllers/lookbook/app_controller.rb

As [mentioned in documentation](https://github.com/allmarkedup/lookbook#blank-preview-window) and handled in configuration, setting `config.preview_srcdoc` should disable `srcdoc` content generation.
The controller did not take into account this flag and always rendered it and made it accessible by the view.
This PR fixes this behavior.
I'm willing to also check in the view if `@preview_srcdoc` is blank to skip outputting `srcdoc=""` altogether.

Stop rendering `srcdoc` preview when it is disabled

---

lib/lookbook/preview.rb

Hi, first of all congratutations. This is a truly gem  :nerd_face: 
I tend to prefer the convention as per https://github.com/palkan/view_component-contrib where components are named Component , previews are named Preview and we put everything on the same folder. This small commit helps with the visualization of such convention, otherwise I get a list of folders named preview on my nav. 
Thanks and regards 
Murilo

Better visualization for preview named Preview 

---

lib/lookbook/preview.rb

This commit allows Preview class names to be like both  SamplePreview and Sample::Preview

Alllow class name to be  simply Preview

---

app/views/lookbook/previews/panels/_params.html.erb

Fix for when the list of parameters in the drawer is too long and overflowing and the panel is not scrollable.

Fix not scrollable overflowing long params list

---

app/helpers/lookbook/application_helper.rb

Thanks for the very snazzy view component preview set up. We're really loving it at The Lookout Way.
It looks like this was done in many other places in
c8cf162dd41f42e5d405503764dc007a7a7c97d5.
I'm not _sure_ but I think the difference between our app and the dummy
and demo apps is that we set:
config.action_controller.include_all_helpers = false
Therefore PageHelper isn't automatically loaded for the
PagesController. The ApplicationHelper is manually included in
ApplicationController, but the PageHelper isn't manually included in the
PagesController, where page_path is being called by the landing_path
method, which is being called when rending the branding partial, which
happens as part of PagesController#show.
This diff seems to get our pages rendering again, without it we get a …

Manually prefix route helper in application helper

---

app/views/lookbook/previews/inputs/_select.html.erb
app/views/lookbook/previews/inputs/_text.html.erb
app/views/lookbook/previews/inputs/_textarea.html.erb
app/views/lookbook/previews/inputs/_toggle.html.erb
test/app_integration_test.rb
test/dummy/test/components/previews/param_component_preview.rb

Hi! Thanks for the awesome gem. There was a minor bug that prevented using params with quotes, e.g.:
```ruby
def example(message: "Let's go!")
end
```

fix: Escape quotes in params values

---

app/views/lookbook/pages/show.html.erb

I found that the width for docs content was too narrow. I added a different class name to make it wider:

Replaced max-w-3xl with max-w-screen-lg

---

README.md
lib/lookbook/params.rb

This PR adds [date](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) and [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) as `@param` input options.
These are both types of `<input>` tags so didn't think it was necessary to add new erb files for the previews.

Updating input params to accept date related inputs

---

app/views/lookbook/previews/panels/_preview.html.erb

**Before:** ↔️ (same as horizontal resize)
**After:** ↕️

Use correct cursor for vertical resize

---

app/controllers/lookbook/application_controller.rb

Rails applications that use the their Content Security Policy also in the development environment are likely to block and break Lookbook. When that happens, all the user sees is a blank white page, and some errors in the browser console :eyes: 
This change disables any CSP in the Lookbook controllers, but only in development. Production environments are not impacted.

Disable CSP in development environment

---

docs/src/guide/quick-start.md

Just a quick docs fix of the annotations link in quick-start.md (/guide/previews/annotating vice /guide/previews/annotations)

Docs: Fix broken annotations link in quick start

---

docs/src/guide/previews/params.md

Congrats on the 1.0 launch!
I noticed the docs site was missing the input options added in https://github.com/allmarkedup/lookbook/pull/116
I'm adding the param options here

Updating docs site for date and datetime-local input options

---

docs/src/guide/index.md

Adds a new section that lists the companies that are using Lookbook. I've copied the structure used by the [ViewComponents](https://viewcomponent.org/#who-uses-viewcomponent) project.
Closes https://github.com/allmarkedup/lookbook/issues/111
I work for [Clio](https://www.clio.com/) and can verify that we do indeed use and love Lookbook!

Add list of companies who use Lookbook to docs homepage

---

app/controllers/lookbook/application_controller.rb

The `content_security_policy` method isn't available in Rails <= 5.1 so using lookbook >= 0.9.7 fails on older version of Rails. This PR checks that `content_security_policy` is available before trying to call it. This _should_ ensure compatibility with older versions of Rails 🤞 I'll open another PR or an issue if I find anything else.

fix: Conditionally call `content_security_policy`

---

docs/src/guide/index.md

Adding [Within3](https://within3.com/) to the **Who uses Lookbook?** section of the docs. Thanks again for all your work on this!

chore: Add Within3 to list of companies using lookbook

---

docs/src/_data/config_options.yml
lib/lookbook/config.rb
lib/lookbook/preview_controller.rb

Rails allows you to set a config option named `config.action_view.annotate_rendered_view_with_filenames` which will wrap rendered templates in HTML comments indicating the file system path of the file being rendered. This can be useful in dev environments to make it easier to track down where parts of the page are coming from. However it can create a bit of noise when viewing the HTML tab of a component in Lookbook. Below is an example of setting this value to `true` in the workbench app.
This PR introduces a new Lookbook config setting to generate this source without these annotations in the event the setting is enabled. Setting `config.lookbook.disable_action_view_annotations = true` will generate the source without them.
I made this a configuration setting in the event there are folks …

Add config option to disable action_view annotations

---

lib/lookbook/theme.rb

In `lib/lookbook/theme.rb:44` it checks `key.start_with?("favicon")`. Unfortunately, `key` is a symbol and support for `start_with?` for symbols wasn't added until Ruby 2.7
Sorry to be constantly opening PR's to support older versions of Ruby but Lookbook has be super awesome for us and we'd love to keep using it! Hopefully after we update I can start contributing real features and not just patches ❤️ 
I also did a minor syntax change from `select` to `reject` for filtering since I think it's a little clearer to reject keys that start with "faviocon" rather than select keys that dont start with favicon.  But this might just be my preference so I can roll it back if you want.
Thanks for all you do!

fix: Ensure key is a string for `start_with?`

---

app/components/lookbook/base_component.rb
app/components/lookbook/button/component.html.erb
app/components/lookbook/button_group/component.rb
app/components/lookbook/copy_button/component.html.erb
app/components/lookbook/embed/component.html.erb
app/components/lookbook/header/component.html.erb
app/components/lookbook/nav/component.rb
app/components/lookbook/nav/item/component.html.erb
app/components/lookbook/nav/item/component.rb
app/components/lookbook/page_tabs/component.html.erb
app/components/lookbook/page_tabs/component.rb
app/components/lookbook/tabs/component.html.erb
app/helpers/lookbook/component_helper.rb
app/helpers/lookbook/page_helper.rb
app/views/layouts/lookbook/application.html.erb
app/views/layouts/lookbook/page.html.erb
app/views/layouts/lookbook/shell.html.erb
app/views/lookbook/error.html.erb
app/views/lookbook/pages/show.html.erb
app/views/lookbook/previews/panels/_content.html.erb
app/views/lookbook/previews/panels/_notes.html.erb
app/views/lookbook/previews/panels/_output.html.erb
app/views/lookbook/previews/panels/_params.html.erb
app/views/lookbook/previews/panels/_preview.html.erb
app/views/lookbook/previews/panels/_source.html.erb
app/views/lookbook/previews/show.html.erb

Fixes #156 which was caused by Lookbook relying on the `render` method to render its own components - however older Rails versions with the VC monkey patch disabled need to use the `render_component` method instead.

Fix errors when VC monkey patch is disabled in older Rails versions

---

docs/src/_data/config_options.yml
lib/lookbook/config.rb
lib/lookbook/engine.rb

Our local development environment uses a verbose logging level and the Lookbook logs are adding quite a bit of extra stuff to them. I'm proposing a new configuration option that would let us tell Lookbook not to use the Rails logger even though we're running inside a Rails app. This will give us a bit more control over our logs.
I've defaulted the value to `true` so it should match the existing behavior.

Add config option to make rails logger optional

---

Gemfile.lock
gemfiles/rails_6.0.gemfile.lock
gemfiles/rails_6.1.gemfile.lock
gemfiles/rails_7.0.gemfile.lock
lib/lookbook.rb
lib/lookbook/config.rb
lib/lookbook/engine.rb
lookbook.gemspec

Removes all the ugly manual `require` and `autoload` calls and delegates to Zeitwerk to handle autoloading instead.

Use Zeitwerk for autoloading

---

config/tags.yml
lib/lookbook/preview.rb
lib/lookbook/source_inspector.rb
lib/lookbook/tags/logical_path.rb
spec/dummy/test/components/previews/annotated_component_preview.rb
spec/entities/preview_example_spec.rb
spec/entities/preview_spec.rb
spec/system/preview_navigation_spec.rb

As per discussion in https://github.com/ViewComponent/lookbook/pull/207 this adds a new tag `@logical_path` which can be used to relocate previews within the nav tree.
The `@logical_path` value should be the path to the nav directory that the preview should be displayed in. The provided path does not have to really exist in the app itself, it is just a virtual construct.
```rb
class Elements::AvatarComponentPreview < ViewComponent::Preview  
#...
end
```

Add @logical_path tag

---

app/components/lookbook/nav/item/component.html.erb
app/components/lookbook/split_layout/component.html.erb

- Fix `Nav::Item::Component` width.
- Fix `SplitLayout::Component` resize handler `z-index` to be over `Source` panel.

Fix split layout and nav item style

---

config/tags.yml
docs/src/_components/shared/method_info.html.erb
docs/src/_data/tags.yml
lib/lookbook/entities/concerns/inspectable.rb
lib/lookbook/entities/preview_example.rb
lib/lookbook/lang.rb
lib/lookbook/rendered_example.rb
lib/lookbook/services/data/resolvers/data_resolver.rb
lib/lookbook/tags/source_tag.rb
lib/lookbook/tags/yard_tag.rb
spec/dummy/test/components/previews/custom_source_component_preview.rb
spec/dummy/test/components/previews/nested/my_component/component.js
spec/lib/tags/source_tag_spec.rb
spec/system/output_panel_spec.rb
spec/system/source_panel_spec.rb

The `@source` tag allows users to override the contents of the `Source` tab by providing a path to a file whose content should be used instead.
The path will be resolved relative to...
* ... the **preview file** that the tag is defined in if it begins with a dot (e.g. `./component.js`)
* ... the **preview base directory** for all other paths.
```ruby
class Frontend::ExampleComponentPreview
def example_one
end
def example_two
end
end
```

Add `@source` tag

---

app/components/lookbook/nav/component.rb
app/views/layouts/lookbook/application.html.erb

We use lookbook in production as a documentation website for [Polaris ViewComponents](https://polarisviewcomponents.org). The loading time on production was pretty slow (2-3 seconds for the initial inspector load). After diving into the problem I noticed that the main source of the issue is sidebar generation. It was called 3 times for each request and generation itself takes some time for a large preview list. To optimize this I made two changes:
1. Added memoization for tree generation in the Nav component. It's called 3 times per request so it's a big win in development mode.
2. I added caching for the whole lookbook sidebar. It makes loading fast on production as we don't need to regenerate the tree each time.

Performance improvements

---

lookbook.gemspec

Lookbook isn't compatible with apps running Ruby < 2.7 so we should update the gemspec to reflect that. At present you can install lookbook in an app running <2.7 without any bundler errors but will cause booting the app to fail. Updating the gemspec will stop people with unsupported ruby versions from installing in the first place.

chore: Require Ruby version 2.7 or higher

---

docs/src/guide/extend/inputs.md

A small fix to the documentation site where a path was accidentally set as an absolute path to localhost

Fix path to input types documentation

---

docs/src/guide/previews/display.md

apidock is out-of-date, it only goes up to Rails 6.1.3.1 which was released in 2021, much better to link directly to the latest official Rails docs.

Link to official Rails docs instead of apidock

---

app/helpers/lookbook/page_helper.rb

The `include Utils` line in `PageHelper` seems to be a leftover from a refactor. The `Utils` module has no methods of its own, only its singleton class has methods. So including `Utils` into any class will not have any effect, which makes this include redundant.

Remove redundant `Utils` include

---

app/components/lookbook/viewport/component.html.erb

I'm working on a panel that runs axe tests on the preview. To accomplish this, I pass the `iframe` element to `axe.run`. Currently this always produces a violation because the iframe is missing a `title` (see https://dequeuniversity.com/rules/axe/4.6/frame-title). This will let me avoid having to filter out the violation and it improves Lookbook's accessibility (which I gotta say isn't great at the moment, a lot of unlabelled buttons).

Add `title` to `iframe` in `Viewport::Component`

---

app/controllers/lookbook/application_controller.rb
app/controllers/lookbook/previews_controller.rb
config/routes.rb
docs/src/api/json_endpoints.md
spec/requests/application_spec.rb

This change introduces a JSON endpoint that returns a machine-readable representation of the previews and examples served by Lookbook.
I'm introducing this feature so that Lookbook deployments can be crawled by our automated tooling at GitHub.

Add JSON endpoint for listing previews and examples

---

app/controllers/lookbook/previews_controller.rb

Oftentimes, applications will customize [`X-Frame-Options`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) via `config.action_dispatch.default_headers`, setting it to `DENY` (similar to the `frame-ancestors` CSP directive). While a pretty good idea for most applications, Lookbook depends on rendering within an iframe, and so should not include that header!
This is similar to Lookbook not including `Content-Security-Policy`.

Stop sending `X-Frame-Options`

---

app/controllers/lookbook/previews_controller.rb
docs/src/api/json_endpoints.md
lib/lookbook/entities/preview_example.rb
lib/lookbook/entities/preview_group.rb
spec/entities/preview_example_spec.rb
spec/entities/preview_group_spec.rb
spec/requests/application_spec.rb

I'd like to expose the preview_path for previews in the JSON endpoint I recently added.
Add a `preview_path` method to `Lookbook::Preview` and expose it via the API. I also exposed `lookup_path`. 
Note that in doing this I realized that the API does not handle preview groups, so I added some basic support for them here. @allmarkedup is infinite nesting allowed for preview groups? If so, we likely need to rethink this API entirely.
This controller method is getting a little messy. While I don't think we need to refactor it now, I think we're on the path towards needing a serializer or something similar.

add preview_path to JSON endpoint

---

app/views/layouts/lookbook/application.html.erb
lib/lookbook/engine.rb

Implements a pretty crude fragment cache expiration strategy to help fix the issue outlined in #303 whereby enabling Rails' cache in development prevents Lookbook's nav from updating after changes.

Expire fragment cache after changes

---

app/views/lookbook/inspector/show.html.erb
config/app.yml
config/routes.rb
docs/src/_data/config_options.yml
docs/src/_guide/sharing/embeds.md

While I definitely understand the appeal of the new preview embeds functionality, it would be great if the feature could be disabled in case you don't want to expose that kind of functionality!

Allow preview embeds to be disabled

---

app/components/lookbook/page_tabs/component.html.erb
app/views/lookbook/pages/show.html.erb

v3 of ViewComponent requires `renders_many` slots to use `with_tab` rather than just `tab`. It looks like most (or all) of the other places in the codebase already used `with_` to call, but there were a few places within tabs that didn't.

Updating renders many calls to use with

---

docs/src/_components/lookbook_docs/method_list/component.html.erb

Currently titles in `toc` are clickable, but `method_list` titles do not behave as anchors (they don't have an ID), so nothing happens when you click them.

docs: Allow method_list titles to be used as anchors

---

app/components/lookbook/params/field/component.rb

I ran into an issue where trying to put a paragraph of text including single quotes (`'`) as the default value for a param ended up with the text param showing "undefined" in the UI. Looking into `json_escape`, it is expecting to escape double quotes not single quotes, so I changed the code here to use escaped double quotes instead of single quotes.
Running this locally fixes the issue for me.

Use double quotes to fix escape issues

---

app/controllers/concerns/lookbook/targetable_concern.rb
config/tags.yml
lib/lookbook/engine.rb
lib/lookbook/entities/preview_entity.rb
lib/lookbook/entities/scenario_entity.rb
lib/lookbook/preview.rb
lib/lookbook/preview_after_render.rb
lib/lookbook/preview_controller_actions.rb
lib/lookbook/tags/after_render_tag.rb
spec/dummy/test/components/previews/after_render_component_preview.rb
spec/dummy/test/components/previews/after_render_view_component_example_preview.rb
spec/lib/tags/after_render_tag_spec.rb
spec/requests/previews_spec.rb

Based on the discussion in #371, here's another take on providing a way for folks to transform the HTML output of a scenario after running the render.
This time through a new tag: `@after_render`. It can be put on the preview class or the scenario method, with the method taking higher priority. You provide the name of a private method to call that will receive one argument, a string of the rendered HTML.
Example:
```ruby
class MyComponentPreview < Lookbook::Preview
def default
render MyComponent.new
end
private
def prepend_test(html)
"<p>test</p>#{html}"
end
end

@after_render scenario output transform

---

lib/lookbook/entities/collections/preview_collection.rb
lib/lookbook/entities/concerns/locatable_entity.rb
lib/lookbook/entities/preview_entity.rb
lib/lookbook/entities/scenario_entity.rb

Makes a few changes to the way that paths are constructed to ensure that previews within [collapsed directories](https://github.com/fxn/zeitwerk/blob/main/README.md#collapsing-directories) display correctly in the navigation.
More details/discussion in the original feature request from @ksweetie here: https://github.com/ViewComponent/lookbook/issues/375

Add support for collapsing preview paths via Zeitwerk

---

docs/src/_data/tags.yml
docs/src/_guide/concepts.md
docs/src/_guide/whats_new.md

It fixes some minor issues in the v2 docs:
- Fix the link to "Using Annotations" on the Get Started > Key Concepts page
- Fix 1 typo on the Other > Tags Reference page
- Fix some typos on the Get Started > What's New page

Fix typos and link in v2 user guide

---

app/controllers/concerns/lookbook/with_preview_controller_concern.rb
lib/lookbook/helpers/preview_helper.rb
lib/lookbook/preview_controller_actions.rb
spec/dummy/app/controllers/blog_controller.rb
spec/dummy/app/views/partials/_helpers_example.html.erb
spec/dummy/app/views/partials/_url_helpers_example.html.erb
spec/dummy/app/views/phlex/helpers_example.rb
spec/dummy/config/routes.rb
spec/dummy/test/components/previews/partial_example_preview.rb
spec/requests/previews_spec.rb

Tweaks path parameters for previews to make it appear that the preview is being rendered by the host app, not the Lookbook engine.

Fix URL helpers in previews

---

public/lookbook-assets/css/lookbook.css

Ran into an error page and noticed the error message ran off the side of the page. This change removes `white-space: nowrap;` from `[data-component="message"] .message-title` to allow for reading the entire error.
**BEFORE**
**AFTER**

Bug Fix: Error message title not wrapping causes text overflow

---

lib/lookbook/runtime_context.rb

I found this problem not because I'm directly using the `console` gem, I actually didn't even realize I had it. But `console` is a dependency of `async` which is likely to be a much more common gem to be used in a Rails app.
The `console` gem defines the constant `Console`.
In the `Lookbook::RuntimeContext`, in order to determine if we're in the Rails console or not, there is a check for `Rails.const_defined?(:Console)`.
This will always return true if the `async` gem is loaded, because even though `Rails::Console` is not found `::Console` is found.
The fix here is to not look in inherited scopes, by passing false as the second argument to `const_defined?`.

Live reload can't be used when console gem is present

---

app/components/lookbook/copy_button/component.html.erb

The copy button component is incompatible with ViewComponent v3.0 since it uses the removed slot setter in its template. This PR updates this component to use the `with_SLOT_NAME` setter.

fix: update copy button icon slot to use ViewComponent SlotsV2

---

Gemfile.lock
lookbook.gemspec

There is an explicit require of `marcel` [here](https://github.com/ViewComponent/lookbook/blob/280c1304ac0028918bed8fba2337c383eaabe3b7/lib/lookbook/services/urls/file_data_uri_encoder.rb#L1), but it is not declared as a dependency of the gem. Otherwise, `marcel` is usually loaded with activestorage.

fix: Add explicit dependency on marcel

---

app/components/lookbook/params/field/component.rb
docs/src/_extend/contributing.md
spec/dummy/test/components/previews/params_component_preview.rb
spec/requests/previews_spec.rb
spec/system/params_editor_spec.rb

I noticed a bug with the new dynamic parameter handling feature where default values containing newlines were breaking the JS. This PR addresses that very simply by escaping newlines. I don't know enough about AlpineJS to know if there's a more elegant way to accomplish this escaping. Happy to adjust if there's something cleaner.

Fix multi-line parameter defaults

---

lib/lookbook/tags/param_tag.rb
spec/lib/tags/param_tag_spec.rb

This PR fixes a two small bugs that I noticed in how descriptions are handled in `@param` tags, particularly when there are tag options containing double-quoted strings.
1. The `DESCRIPTION_MATCHER` regex in `ParamTag` was greedy-matching the paired `"` character. It should be non-greedy. I was getting a description of `Whether this should be on or not" { value_type: "Boolean` on my parameter in the UI.
2. The `DESCRIPTION_MATCHER` was getting passed to `gsub!` rather than `sub!` when it matched, so the tag option string getting passed to `YardTag` looked like `{ choices: [primary, secondary], value_type: }` instead of `{ choices: [primary, secondary], value_type: "Symbol" }` because the `"Symbol"` was being removed by `gsub`.
I added a couple of tests for options in the `ParamTag` spec. …

Fix two small bugs in param tag options parsing.

---

lib/lookbook/services/tags/tag_options_parser.rb
lib/lookbook/tags/param_tag.rb
lib/lookbook/tags/yard_tag.rb

Stops the `@param` tag data resolver running when initialising the tag classes, which was causing some addition unnecessary overhead and a bunch of debug noise when starting Lookbook. See #458 for background.

Fix noisy data resolver on startup

---

lib/lookbook/file_watcher.rb

@allmarkedup I hope you're OK with this proposed change! On application startup, you see one of these messages twice, and it seemed a little chatty.
If someone wants to know which watcher that is used, they can look at `Lookbook.debug_data[:dependencies][:lookbook]` or `Lookbook::Engine.auto_refresh?`.

Silence the `FileWatcher` from always logging the type of watcher

---

lib/lookbook/entities/collections/preview_collection.rb

This reformulates a tiny part of the code to use an existing Ruby method.

Prefer Enumerable#grep to filter by type

---

app/controllers/lookbook/application_controller.rb
app/views/layouts/lookbook/application.html.erb
app/views/lookbook/index.html.erb
config/app.yml
docs/package-lock.json
docs/src/_data/config_options.yml
docs/src/_guide/ui/navigation.md
lib/lookbook/entities/page_entity.rb

This PR adds config options to:
* Customise the order of the nav panels in the sidebar
* Hide or show the search/filter box for both previews and pages
This PR adds a `preview_inspector.sidebar_panels` config option that allows for the reordering (or omitting) of section panels in the Lookbook sidebar.
```ruby
config.lookbook.preview_inspector.sidebar_panels = [:pages, :previews]
```
The default value is `[:previews, :pages]`. [Documentation here](https://deploy-preview-556--lookbook-docs.netlify.app/guide/config#preview_inspector.sidebar_panels)
This PR adds `preview_search` and `page_search` config options to hide or show the filter box UI for previews and pages respectively.
```ruby
config.lookbook.preview_search = false # default: true 
config.lookbook.page_search = true # default: …
```

Sidebar customisation improvements

---

lib/lookbook/preview.rb
lib/lookbook/preview_controller_actions.rb

Fixes the bug outlined in #555 caused by template `assigns` not being passed through when rendering previews.

Ensure `assigns` are handled correctly when rendering previews

---

app/controllers/lookbook/previews_controller.rb

since upgrading to 2.20 I had an error coming from the preview controller
see for details https://github.com/ViewComponent/lookbook/issues/549#issuecomment-1829469384

add safe guard for headers["X-Frame-Options"].upcase

---

app/controllers/lookbook/application_controller.rb
config/app.yml
lib/lookbook/stores/config_store.rb

Per issue #528
Allow opting out of catching errors in the application controller. Allows usage of web_console, better_errors, and other solutions.

Allow disabling of error handling

---

app/components/lookbook/icon/component.html.erb
app/components/lookbook/icon/component.rb

Hey there @allmarkedup 👋 it's me again 😄
A co-worker noticed the Primer Lookbook instance loading quite slowly and discovered there are ~600 SVGs on many of our pages. It looks like Lookbook copies the SVG source onto the page for every icon, which the co-worker surmised is leading to long render times on the server. I noticed Lookbook comes with a sprite that includes all the Lucide icons in the img/ directory, so I thought maybe we could just use that instead?
I tried replacing the SVG source with a `<use>` element, and it seems to work nicely. Page render times seem to be a little speedier too, although I won't know how much impact it has on Primer's Lookbook instance until we deploy to prod.
Let me know what you think 😄

Use the Lucide sprite instead of injecting individual SVGs onto the page

---

docs/src/_extend/other/data.md
docs/src/_guide/previews/display.md
docs/src/_guide/previews/layouts.md

If one uses the suggested layout for the ViewComponent default layout, navigating to `localhost:3000/rails/view_components` will throw an error due to the deeply nested nature of the Lookbook params hash. Using `dig` allows for safe access into the hashes without causing problems if any of the keys don't exist.
Hash#dig was introduced in Ruby 2.3, so will be available in all supported versions of Lookbook.
There's a few other instances of `params[:some][:deep][:key]` in the docs, but I thought this one may be a better target since it could cross the Lookbook boundary to ViewComponent.

Use dig in layouts guide ERB

---

config/app.yml
docs/src/_data/config_options.yml
lib/lookbook/engine.rb
lib/lookbook/reloaders.rb

Hello, we're loving lookbook over at @buildkite.
Recently I've been doing some benchmarking of our application boot times and found that lookbook's eager loading of previews and pages in an `after_initialization` hook contributes ~250ms (~12%) to our boot time* in development, which is the only environment in which we have lookbook configured (for now at least). We have ~35 previews and ~5 pages at the time of writing, and I'm assuming that the time taken will gradually increase linearly as we add more.
I'm proposing a config option to defer the loading of the preview and page data to the first time it's needed, which from scouring the code seemed to be entity lookups when hitting the lookbook routes. This is especially useful when utilising the Rails console, runner, rake tasks etc. …

Feature | `lazy_load_previews_and_pages` config option

---

app/views/lookbook/previews/preview.html.erb

I'm not sure if this is exactly the best approach, and we should probably have appraisal run against phlex v1 & v2 if we want to support both, but this works.
Ideally, I wanted to check against `Phlex::VERSION`, but it seems that isn't autoloaded, so we'd have to put a
```ruby
require "phlex/version" if defined?(Phlex)
```
somewhere.

support the correct params for phlex v2 call method

---

lib/lookbook/engine.rb

Setting `preview_paths` to anything else than `test/components/previews` is broken, because we mutate `ActiveSupport::Dependencies.autoload_paths`.
From the Rails guides:
> Please do not mutate ActiveSupport::Dependencies.autoload_paths;
> the public interface to change autoload paths is config.autoload_paths.
Refs: https://github.com/ViewComponent/view_component/issues/365

Fix setting custom preview_paths

---

app/components/lookbook/filter/component.html.erb

Resolves #613
|before|after|
|--|--|
|<img width="279" alt="スクリーンショット 2024-11-15 18 44 54" src="https://github.com/user-attachments/assets/d76886ef-52ef-4113-9443-575ee73141fe">|<img width="278" alt="スクリーンショット 2024-11-15 18 43 49" src="https://github.com/user-attachments/assets/26984e1a-f226-484a-9968-6771296a25f2">

Adjust size of search filter close button

---

app/components/lookbook/params/field/component.rb

This PR is part of https://github.com/lookbook-hq/lookbook/issues/669. The change attempts to ensure that the parameter value is properly escaped to prevent potential security vulnerabilities, such as XSS.
If the [`escaped_value`](https://github.com/lookbook-hq/lookbook/blob/main/app/components/lookbook/params/field/component.rb#L17-L21) contains the following value or similar then it could lead to XSS:
`"-alert(window.location.href)-"` - The `console.log` would be ran, as the quotes would evaluate to `NaN`, leaving the JavaScript within to be ran (i.e. `paramsInputComponent({name: 'text', value: ""-alert(window.location.href)-""})`.
[Example in Lookbook demo](https://demo.lookbook.build/lookbook/inspect/elements/button/playground?text=%22-alert(123)-%22)
The easiest workaround seemed to …

Add `html_escape` so that code cannot be ran based on URL params

---

app/views/layouts/lookbook/skeleton.html.erb

Adds missing CSRF meta tags so that  HTTP requests from previews don't throw `InvalidAuthenticityToken` exceptions, as reported in #632.

Fix missing CSRF token in previews

---

lib/lookbook/support/utils/utils.rb
spec/support/combustion.rb

In some environments, if the config files are not explicitly set to use UTF-8, the strings passed to `page_paths` goes encoded as ASCII and the engine pass this down to Ruby's Dir[] method which returns filenames in the same encoding:
```ruby
Dir['/*'.force_encoding(Encoding::ASCII_8BIT)].map { [_1, _1.encoding] }
=> [
["/bin",  #<Encoding:ASCII-8BIT>],
["/boot", #<Encoding:ASCII-8BIT>],
["/dev",  #<Encoding:ASCII-8BIT>],
["/etc",  #<Encoding:ASCII-8BIT>],
...
```
```ruby
Dir['/*'.force_encoding(Encoding::UTF_8)].map { [_1, _1.encoding] }
=> [
["/bin",  #<Encoding:UTF-8>],
["/boot", #<Encoding:UTF-8>],
["/dev",  #<Encoding:UTF-8>],
["/etc",  #<Encoding:UTF-8>],
...
```
At some point, we pass down these filenames through Rails' String#parameterize, which tries to transliterate it assuming …

Fix 667: "Cannot transliterate strings with ASCII encoding" during rails start

---

app/views/lookbook/inspector/panels/_notes.html.erb

Just a silly styling fix that was bothering me xD
Before:
The container was set to a fixed size, so when the notes had more than a few lines, they were overflowing, messing up the spacing and losing the background
After:
The container height is now set to fit the content, so spacing and background stay intact

Fix height style for notes panel in Lookbook inspector

---

lib/lookbook/engine.rb

Attempts to fix the issues with the ViewComponent v4 compatibility changes made in `v2.3.10`.
Refactors the changes to have one logical branch dedicated to the newer ViewComponent >= v4 config style and one to handle the previous (ViewComponent < v4) config style, which has been reverted to be the same as it was prior to the `v2.3.10` Lookbook release. It's more verbose this way but (IMO) easier to follow and should fix the issues that people have been reporting.

Fixes for ViewComponent v4 config compatibility

---

lib/lookbook/preview_parser.rb

Closes https://github.com/lookbook-hq/lookbook/issues/699
**Context:** When `lazy_load_previews_and_pages` is enabled, [the initial loading of previews is delayed until they are first requested](https://github.com/lookbook-hq/lookbook/blob/e27bbe852e325f0046c04ec4a04e70b3c74be9ee/lib/lookbook/engine.rb#L239-L253).
**Problem:** The existing preview parsing logic uses an instance variable as a boolean flag to prevent concurrent parsing operations. However, this approach has two issues:
1. It's not truly atomic, creating potential race conditions
2. When a second thread attempts to parse while another is already parsing, it simply skips parsing entirely rather than waiting
This race condition is primarily exposed when `lazy_load_previews_and_pages` is enabled. If a "parse changed files" …

Fix preview parsing race condition with `lazy_load_previews_and_pages`
