lookbook-hq/lookbook

- app/controllers/lookbook/browser_controller.rb
We use a custom view component controller to load custom view helpers in previews.
> Respect selected preview controller

- README.md
The README is not too clear on how to configure things to view lookbook in production (there are two settings that need to be changed from defaults to make it work).
This update makes those two settings/changes clearer (it had me stumped for a while till I figured it out).
> Update instructions for mounting in production mode

- app/controllers/lookbook/previews_controller.rb
- lib/lookbook/page.rb
- lib/lookbook/preview.rb
This fixes exception when raising errors with ruby version > 3 . < 3 untested
> Fixes exception when raising error 😜

- README.md
Just a tiny adjustment to the latest default setup of ViewComponent.
This was changed in https://github.com/github/view_component/pull/1117
and then released in https://github.com/github/view_component/releases/tag/v2.43.0.
Thanks for this wonderful enhancement to ViewComponent. 🎉
> README: Streamline suggested gem installation

- README.md
- lib/lookbook/engine.rb
Fixes: https://github.com/allmarkedup/lookbook/issues/103
Thanks for the neat gem. I'm looking at using this in a new project and this seemed like an easy win :)
> Add ability to specify extra listen extensions

- docs/src/guide/index.md
Adding FreeAgent to the list of Lookbook users
> Adding FreeAgent to the list of Lookbook users

- lib/lookbook/markdown.rb
- lib/lookbook/preview_controller.rb
- lib/lookbook/utils.rb
> Ensure action view annotations are correctly removed from preview layouts

- app/components/lookbook/params/editor/component.html.erb
- app/views/lookbook/inspector/panels/_notes.html.erb
- app/views/lookbook/inspector/panels/_params.html.erb
Unify `padding` and `width` across all panels.
> Unify panels spacing and sizes

- docs/src/guide/index.md
> Spell GitHub correctly

- lib/lookbook/entities/collections/preview_collection.rb
- lib/lookbook/entities/concerns/locatable.rb
> view_component-contrib compatibility fixes

- app/views/lookbook/inspector/show.html.erb
> Fixes #259 in rendering inspector with erb preview template

- docs/src/_guide/installation.md
Fixes a typo in Gemfile example
> Updates installation.md Gemfile

- lib/lookbook/engine.rb
Fix issue introduced in https://github.com/rails/rails/commit/7b5e2f3d2cc59fc4001226ed1053a61456525853
> ActionView::ViewPaths::Registry to ActionView::PathRegistry

- app/views/lookbook/previews/preview.html.erb
- spec/dummy/app/views/phlex/list_example.rb
- spec/dummy/test/components/previews/phlex_example_preview.rb
- spec/requests/previews_spec.rb
> Fix rendering of builder-style Phlex components

- lib/lookbook/entities/collections/concerns/hierarchical_collection.rb
- lib/lookbook/entities/collections/page_collection.rb
- lib/lookbook/entities/collections/preview_collection.rb
- lib/lookbook/services/entities/page_tree_builder.rb
- lib/lookbook/services/entities/preview_tree_builder.rb
- lib/lookbook/support/utils/path_utils.rb
Fixes issue #443 where page directories with position prefixes were not being correctly ordered in the nav.
> Fix page directory ordering

- lib/lookbook/entities/collections/concerns/hierarchical_collection.rb
- lib/lookbook/entities/collections/preview_collection.rb
An attempt to fix the issue discussed in #311 without causing downstream issues with preview collections.
> Add support for nested component previews

- app/controllers/lookbook/previews_controller.rb
It just small changes for fixing this issue here: https://github.com/ViewComponent/lookbook/issues/549
> Update syntax condition inside method permit_framing

- docs/src/images/icons/lucide_sprite.svg
- public/lookbook-assets/img/lucide-sprite.svg
> fix svg sprite

- lib/lookbook/engine.rb
Resolves [644](https://github.com/lookbook-hq/lookbook/issues/644)
> remove debugging statements

- CONTRIBUTING.md
Hey @allmarkedup, here is the addition to the docs we discussed earlier.
Let me know if you think I should add it to `docs/src/_extend/contributing.md` as well.
> Add docs for releasing a new version

- lib/lookbook/support/utils/utils.rb
- spec/lib/support/utils/utils_spec.rb
- spec/spec_helper.rb
> Fix Ruby 3.4 frozen string deprecation warnings

- .github/workflows/push_gem.yml
- CONTRIBUTING.md
- bin/release
- lookbook.gemspec
> Setup Trusted Publishing

- Gemfile
- Gemfile.lock
- app/views/lookbook/previews/preview.html.erb
- spec/requests/previews_spec.rb
> Fix Phlex version identification
